export const FETCH_GENRE = "FETCH_GENRE";
export const FETCH_GENRE_START = "FETCH_GENRE_START";
export const FETCH_GENRE_SUCCESS = "FETCH_GENRE_SUCCESS";
export const FETCH_GENRE_FAILED = "FETCH_GENRE_FAILED";
