export const FETCH_GENRE = "FETCH_GENRE";
export const FETCH_GENRE_START = "FETCH_GENRE_START";
export const FETCH_GENRE_SUCCESS = "FETCH_GENRE_SUCCESS";
export const FETCH_GENRE_FAILED = "FETCH_GENRE_FAILED";

export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const SEARCH_MOVIES_START = "SEARCH_MOVIES_START";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_FAILED = "SEARCH_MOVIES_FAILED";
