export const FETCH_GENRE = "FETCH_GENRE";
export const FETCH_GENRE_START = "FETCH_GENRE_START";
export const FETCH_GENRE_SUCCESS = "FETCH_GENRE_SUCCESS";
export const FETCH_GENRE_FAILED = "FETCH_GENRE_FAILED";

export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const SEARCH_MOVIES_START = "SEARCH_MOVIES_START";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_FAILED = "SEARCH_MOVIES_FAILED";

export const FETCH_MORE_MOVIES = "FETCH_MORE_MOVIES";
export const FETCH_MORE_MOVIES_START = "FETCH_MORE_MOVIES_START";
export const FETCH_MORE_MOVIES_SUCCESS = "FETCH_MORE_MOVIES_SUCCESS";
export const FETCH_MORE_MOVIES_FAILED = "FETCH_MORE_MOVIES_FAILED";

export const SELECT_MOVIE = "SELECT_MOVIE";
export const SELECT_MOVIE_START = "SELECT_MOVIE_START";
export const SELECT_MOVIE_SUCCESS = "SELECT_MOVIE_SUCCESS";
export const SELECT_MOVIE_FAILED = "SELECT_MOVIE_FAILED";
export const SELECT_MOVIE_REMOVE = "SELECT_MOVIE_REMOVE";
